AWSTemplateFormatVersion: '2010-09-09'
Description: Ec2 instance that will host the discord script
Resources:
  RageContainer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02354e95b39ca8dec
      InstanceType: t2.micro
      KeyName: discord
